### ISSUE TITLE
Directories with 3 dotted version numbers not handled

### ISSUE THREAD

**Issue by IvanMalison** [flycheck/flycheck-cask#3]
Cask seems to be creating directories with 3 dotted version numbers for me e.g.:

```
⚡ imalison at imalison-arch in ~/Projects/multi-line/.cask on recursive_find✘
± ❯ ls -altr
total 12
drwxr-xr-x 3 imalison users 4096 Sep  3 17:32 24.5.1
drwxr-xr-x 3 imalison users 4096 Sep  3 17:32 .
drwxr-xr-x 5 imalison users 4096 Sep  7 14:48 ..
```

But flycheck cask is setting
`flycheck-emacs-lisp-package-user-dir` to `"/home/imalison/Projects/multi-line/.cask/24.5/elpa"`

It seems like this is a case that should be handled.

**Comment by lunaryorn** [comment]
The latest Cask release uses only the major and minor version.  The third version number has no meaning in Emacs… it's just a build number.
